In [4]:
import pymysql
from sqlalchemy import create_engine
import pandas as pd

In [11]:
sqlEngine       = create_engine('mysql+pymysql://root:secret@127.0.0.1/football_data', pool_recycle=3600)
dbConnection    = sqlEngine.connect()

In [77]:
df_matches = pd.read_sql_query("SELECT * FROM matches", sqlEngine)
df_stats_matches_home_total = pd.read_sql_query("SELECT * FROM stats_matches WHERE ID like '%HT'", sqlEngine)
df_stats_matches_home_first = pd.read_sql_query("SELECT * FROM stats_matches WHERE ID like '%H1'", sqlEngine)
df_stats_matches_home_second = pd.read_sql_query("SELECT * FROM stats_matches WHERE ID like '%H2'", sqlEngine)
df_stats_matches_away_total = pd.read_sql_query("SELECT * FROM stats_matches WHERE ID like '%AT'", sqlEngine)
df_stats_matches_away_first = pd.read_sql_query("SELECT * FROM stats_matches WHERE ID like '%A1'", sqlEngine)
df_stats_matches_away_second = pd.read_sql_query("SELECT * FROM stats_matches WHERE ID like '%A2'", sqlEngine)

In [78]:
df_stats_matches_home_total.describe()

,BALL_POSSESSION,GOAL_ATTEMPTS,SHOTS_ON_GOAL,SHOTS_OFF_GOAL,BLOCKED_SHOTS,FREE_KICKS,CORNERS,OFFSIDES,THROW_IN,GOALKEEPER_SAVES,FOULS,YELLOW_CARDS,RED_CARDS,COMPLETED_PASSES,TACKLES,ATTACKS,DANGEROUS_ATTACKS
count,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000,11534.000000
mean,51.203139,13.422924,4.897174,5.625802,2.899775,13.359979,5.489856,2.138287,5.836570,2.818797,12.742154,1.998353,0.088954,206.911392,8.204439,68.279261,33.497659
std,10.938383,5.210417,2.690969,2.839518,2.384234,6.116781,2.967618,1.738532,10.309218,1.940663,4.159350,1.405017,0.304128,245.419007,8.742578,57.118454,30.706146
min,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,44.000000,10.000000,3.000000,4.000000,1.000000,10.000000,3.000000,1.000000,0.000000,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,51.000000,13.000000,5.000000,5.000000,3.000000,14.000000,5.000000,2.000000,0.000000,3.000000,12.000000,2.000000,0.000000,0.000000,7.000000,88.000000,37.000000
75%,59.000000,17.000000,6.000000,7.000000,4.000000,17.000000,7.000000,3.000000,12.000000,4.000000,15.000000,3.000000,0.000000,424.000000,16.000000,115.000000,56.000000
max,84.000000,43.000000,22.000000,23.000000,18.000000,45.000000,20.000000,14.000000,47.000000,15.000000,33.000000,9.000000,3.000000,2288.000000,38.000000,215.000000,169.000000

In [74]:
df_stats_matches_home_first.describe()

,BALL_POSSESSION,GOAL_ATTEMPTS,SHOTS_ON_GOAL,SHOTS_OFF_GOAL,BLOCKED_SHOTS,FREE_KICKS,CORNERS,OFFSIDES,THROW_IN,GOALKEEPER_SAVES,FOULS,YELLOW_CARDS,RED_CARDS,COMPLETED_PASSES,TACKLES,ATTACKS,DANGEROUS_ATTACKS
count,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000,11426.000000
mean,51.383336,6.178365,2.202170,2.625678,1.350429,6.430072,2.615789,1.060564,2.831175,1.281288,6.032645,0.686767,0.019692,106.376772,3.967530,34.295642,15.974532
std,11.642678,3.033128,1.643154,1.746119,1.417764,3.373064,1.860409,1.119631,5.342643,1.240877,2.553872,0.817636,0.143287,127.049739,4.495356,29.393918,15.242614
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,43.000000,4.000000,1.000000,1.000000,0.000000,4.000000,1.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,52.000000,6.000000,2.000000,2.000000,1.000000,7.000000,2.000000,1.000000,0.000000,1.000000,6.000000,1.000000,0.000000,0.000000,2.000000,42.000000,16.000000
75%,60.000000,8.000000,3.000000,4.000000,2.000000,9.000000,4.000000,2.000000,0.000000,2.000000,8.000000,1.000000,0.000000,217.750000,8.000000,58.000000,27.000000
max,87.000000,26.000000,12.000000,12.000000,11.000000,23.000000,12.000000,9.000000,30.000000,9.000000,20.000000,5.000000,2.000000,518.000000,25.000000,116.000000,83.000000

In [66]:
df_stats_matches_home_second.describe()

,BALL_POSSESSION,GOAL_ATTEMPTS,SHOTS_ON_GOAL,SHOTS_OFF_GOAL,BLOCKED_SHOTS,FREE_KICKS,CORNERS,OFFSIDES,THROW_IN,GOALKEEPER_SAVES,FOULS,YELLOW_CARDS,RED_CARDS,COMPLETED_PASSES,TACKLES,ATTACKS,DANGEROUS_ATTACKS
count,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000
mean,50.982377,7.241745,2.695416,2.994927,1.551313,6.924878,2.877882,1.079128,2.976324,1.537695,6.714731,1.313841,0.069248,100.130930,4.228215,33.819938,17.439875
std,12.276430,3.512148,1.874411,1.960095,1.608770,3.650703,2.056321,1.132438,5.600663,1.371549,2.784509,1.156885,0.268871,121.938488,4.794224,29.360981,16.942399
min,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,42.000000,5.000000,1.000000,2.000000,0.000000,5.000000,1.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,51.000000,7.000000,2.000000,3.000000,1.000000,7.000000,3.000000,1.000000,0.000000,1.000000,7.000000,1.000000,0.000000,0.000000,3.000000,41.000000,17.000000
75%,60.000000,9.000000,4.000000,4.000000,2.000000,9.000000,4.000000,2.000000,5.000000,2.000000,8.000000,2.000000,0.000000,204.000000,8.000000,58.000000,30.000000
max,96.000000,24.000000,15.000000,15.000000,13.000000,29.000000,16.000000,7.000000,39.000000,10.000000,20.000000,7.000000,3.000000,2114.000000,29.000000,139.000000,96.000000

In [67]:
df_stats_matches_away_total.describe()

,BALL_POSSESSION,GOAL_ATTEMPTS,SHOTS_ON_GOAL,SHOTS_OFF_GOAL,BLOCKED_SHOTS,FREE_KICKS,CORNERS,OFFSIDES,THROW_IN,GOALKEEPER_SAVES,FOULS,YELLOW_CARDS,RED_CARDS,COMPLETED_PASSES,TACKLES,ATTACKS,DANGEROUS_ATTACKS
count,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000
mean,48.820116,11.035781,4.034624,4.610414,2.390743,13.347308,4.508411,1.945972,5.597241,3.363863,13.009079,2.252247,0.112417,196.395728,8.335470,63.536093,28.577392
std,10.916728,4.618638,2.368371,2.568724,2.093222,6.146329,2.614001,1.647183,9.908260,2.204123,4.231370,1.447162,0.334772,232.445803,8.861728,53.556208,26.558097
min,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,41.000000,8.000000,2.000000,3.000000,1.000000,10.000000,3.000000,1.000000,0.000000,2.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,49.000000,11.000000,4.000000,4.000000,2.000000,14.000000,4.000000,2.000000,0.000000,3.000000,13.000000,2.000000,0.000000,0.000000,8.000000,81.000000,31.000000
75%,56.000000,14.000000,5.000000,6.000000,4.000000,17.000000,6.000000,3.000000,12.000000,5.000000,16.000000,3.000000,0.000000,403.000000,16.000000,107.000000,48.000000
max,82.000000,32.000000,17.000000,21.000000,15.000000,39.000000,19.000000,14.000000,50.000000,20.000000,32.000000,9.000000,3.000000,993.000000,38.000000,241.000000,135.000000

In [68]:
df_stats_matches_away_first.describe()

,BALL_POSSESSION,GOAL_ATTEMPTS,SHOTS_ON_GOAL,SHOTS_OFF_GOAL,BLOCKED_SHOTS,FREE_KICKS,CORNERS,OFFSIDES,THROW_IN,GOALKEEPER_SAVES,FOULS,YELLOW_CARDS,RED_CARDS,COMPLETED_PASSES,TACKLES,ATTACKS,DANGEROUS_ATTACKS
count,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000
mean,48.635603,4.989853,1.810503,2.101914,1.077348,6.357810,2.101825,0.974722,2.705919,1.524344,6.214597,0.798665,0.024922,100.061415,4.042902,31.506987,13.295683
std,11.629557,2.717663,1.483983,1.572425,1.243526,3.356398,1.651374,1.078246,5.103246,1.372175,2.599174,0.850210,0.157598,119.911548,4.583987,27.254970,12.948102
min,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,40.000000,3.000000,1.000000,1.000000,0.000000,4.000000,1.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,48.000000,5.000000,2.000000,2.000000,1.000000,6.000000,2.000000,1.000000,0.000000,1.000000,6.000000,1.000000,0.000000,0.000000,2.000000,38.000000,13.000000
75%,57.000000,7.000000,3.000000,3.000000,2.000000,9.000000,3.000000,2.000000,0.000000,2.000000,8.000000,1.000000,0.000000,204.000000,8.000000,53.000000,22.000000
max,98.000000,18.000000,11.000000,12.000000,10.000000,22.000000,11.000000,8.000000,28.000000,10.000000,17.000000,6.000000,2.000000,530.000000,27.000000,138.000000,67.000000

In [69]:
df_stats_matches_away_second.describe()

,BALL_POSSESSION,GOAL_ATTEMPTS,SHOTS_ON_GOAL,SHOTS_OFF_GOAL,BLOCKED_SHOTS,FREE_KICKS,CORNERS,OFFSIDES,THROW_IN,GOALKEEPER_SAVES,FOULS,YELLOW_CARDS,RED_CARDS,COMPLETED_PASSES,TACKLES,ATTACKS,DANGEROUS_ATTACKS
count,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000,11235.000000
mean,49.018247,6.045928,2.224032,2.508500,1.313396,6.989497,2.406587,0.971251,2.891322,1.839519,6.794482,1.453583,0.087494,96.178015,4.286871,32.029105,15.281709
std,12.276216,3.149448,1.656959,1.798362,1.425671,3.710250,1.834692,1.079603,5.404143,1.551606,2.800571,1.194930,0.297008,115.820785,4.828226,27.804596,15.026294
min,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,40.000000,4.000000,1.000000,1.000000,0.000000,5.000000,1.000000,0.000000,0.000000,1.000000,5.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,49.000000,6.000000,2.000000,2.000000,1.000000,7.000000,2.000000,1.000000,0.000000,2.000000,7.000000,1.000000,0.000000,0.000000,3.000000,39.000000,15.000000
75%,58.000000,8.000000,3.000000,4.000000,2.000000,9.000000,3.000000,2.000000,5.000000,3.000000,9.000000,2.000000,0.000000,195.000000,8.000000,54.000000,26.000000
max,87.000000,20.000000,11.000000,15.000000,11.000000,28.000000,14.000000,10.000000,41.000000,13.000000,21.000000,8.000000,3.000000,658.000000,27.000000,147.000000,100.000000

In [53]:
df_matches.describe()

,ROUND,GOALS_H,GOALS_A,ODDS_HOME,ODDS_HOME_X,ODDS_AWAY,ODDS_AWAY_X,TEMPERATURE,RAIN,HUMIDITY,CLOUDY,WIND
count,10140.000000,10140.000000,10140.000000,10140.000000,10140.000000,10140.000000,10140.000000,10140.000000,10140.000000,10140.000000,10140.000000,10140.000000
mean,19.310750,1.549310,1.218540,2.877655,1.527688,4.791648,2.061860,13.438067,0.418767,68.116469,44.014694,13.785700
std,10.721215,1.306336,1.167571,2.261905,0.662932,4.376316,1.212616,7.188445,1.394522,17.063152,35.760351,8.903618
min,1.000000,0.000000,0.000000,-1.000000,0.490000,-1.000000,0.490000,-11.000000,0.000000,11.000000,0.000000,0.000000
25%,10.000000,1.000000,0.000000,1.650000,1.150000,2.300000,1.370000,8.000000,0.000000,57.000000,9.000000,7.000000
50%,20.000000,1.000000,1.000000,2.200000,1.320000,3.400000,1.680000,13.000000,0.000000,70.000000,36.000000,12.000000
75%,28.000000,2.000000,2.000000,3.100000,1.630000,5.500000,2.250000,18.000000,0.200000,82.000000,79.000000,18.000000
max,38.000000,9.000000,9.000000,26.000000,8.660000,41.000000,14.370000,43.000000,32.200000,100.000000,100.000000,65.000000